### ISSUE TITLE
Highlight in lambda is not smart

### ISSUE THREAD

**Issue by YouheiLee** [csense-oss/idea-kotlin-checked-exceptions#2]
Extremely grateful to you for the plugin! It is very useful, but I found a problem:
Assume that I have a function foo
```
@Throws(IOException::class)
fun foo(param: Any) {
    handled {
        throwIOExceptionFun()
    }
}
```
And the "handled" is a function like
```
@Throws(IOException::class)
fun throwable(block: () -> Unit) {
    try {
        block.invoke()
    } catch (e: IOException) {
        throw e
    }
}
```
In this case, function foo() still has highlight at "throwIOExceptionFun()" because plugin don't know that exception was handled already.

**Comment by YouheiLee** [comment]
I made a mistake. The plugin works fun, I use it with a wrong way.

**Comment by Tvede-dk** [comment]
Hi, 
You are welcome :) glad you like it.
Now there are 2 "features" that tries to handle theses type of scenarios with lambdas, which is 
callthought (meaning that the given lambda is not stored but just used in the given function)
and "ignore" which is when you have say a library function or alike that catches everything (thus the name ignore).

So if you add handled / throwable in your example, to the "callthough file" 
![image](https://user-images.githubusercontent.com/5425815/87222820-9239af80-c377-11ea-8334-c842572b76ff.png)
then any try catch around the handled would work. (and or the throws annotation). 
Is this what you are asking for ? 
(this is quite complex to otherwise solve automatically since idea does not necessary have access to sources and thus external code cannot be done automatically, but also the performance of trying to detect whenever a function stores or not a lambda would be quite bad, its already not too good, but that will be improved later :) )

**Comment by YouheiLee** [comment]
Thank you for your reply, That's very useful.
