### ISSUE TITLE
Need icons for dark IDEA theme

### ISSUE THREAD

**Issue by tanmatra** [csense-oss/idea-kotlin-checked-exceptions#4]
Current icons are too bright.

Also, they are too blurry, especially on HiDPI screen.

**Comment by Tvede-dk** [comment]
Which icons are you referring to exactly ? I use a dark theme and its not any more bright than any other icons ? There is only 2 icons, so a guess is that you have a 4k display with a very high brightness level ? 
I can experiment with "less" brighter colors, but only to a certain degree. Maybe you can provide some feedback / info regards what colors would be "okay" ? (eg just via paint or whatever drawing application you can use). ? 

I will update the icons to svg. :)

**Comment by tanmatra** [comment]
You can compare with some standard IDEA icon, it's smaller and its color is less saturated, so it attracts less attention to the eyes.

![image](https://user-images.githubusercontent.com/708023/90128856-41e7b000-dd70-11ea-8e89-e378729d727a.png)

**Comment by tanmatra** [comment]
Oh no, in the new version it's even more bigger and brighter...
Looks like a street full of red signals.

![image](https://user-images.githubusercontent.com/708023/90235825-994a5680-de2a-11ea-8f7d-8aaa4555ce3e.png)

**Comment by Tvede-dk** [comment]
No they are not "brighter" they are more saturated, but less "bright". They are bigger so that the arrow was still visible. 
(kept around the same colors so that people who have been using it for almost a year would still recognize it) 

If you do not want the gutter icon there is even a setting to turn them off.
![image](https://user-images.githubusercontent.com/5425815/90248739-8d19c580-de39-11ea-93d1-d653df403636.png)


If you have any icon that you prefer I can take a look, until then, I cannot tell when I will come around to make the icon follow the IDEA design guide completely. 
There is no need to state your disagreement multiple times, I do this for free, in my spare time, so be a bit respectful of that (if it was paid in any way the story would be completely different)

**Comment by Tvede-dk** [comment]
What are your thoughts on the new version ? :)
