### ISSUE TITLE
error mark function place

### ISSUE THREAD

**Issue by zomb-676** [csense-oss/idea-kotlin-checked-exceptions#9]
![4](https://user-images.githubusercontent.com/26162862/123546942-4c951300-d791-11eb-9234-a7ff8c1fe71a.gif)
plugin version:1.1.4(latest)
idea version:2021.1.2(latest)

**Comment by Tvede-dk** [comment]
Should be "fixed" in 2.0. The short answer is that the plugin (as of now) does not know all the intrinsic of which functions are "callthough" (e.g. calls in place) and which one captures the exceptions. So if the plugin is unable to read any contracts &/ annotations (2.0) then it would first need to know that a lambda argument is callthough. then it should also be able to highlight the call instead of inside of the lambda (as it is the call now that will throw).
